### ISSUE TITLE
使用自定义配置无效而默认配置有效

### ISSUE THREAD

**Issue by windingwind** [Banlangenn/vue-savedata#2]
使用样例中的自定义方式添加部分模块到LS，并如样例添加到plugin后，在浏览器的localstorage没有看到数据，也没有任何错误信息（其他一切正常）；而直接使用默认方式有效。
无效代码如下：（省略了不相关内容）
``` js
import createPersiste from 'vue-savedata';
import userModule from './modules/user';

const p = createPersiste({
  LS: {
    module: userModule,
    storePath: 'user',
  },
});

export default new Vuex.Store({
  modules: {
    user: userModule,
    source: sourceModule,
    manage: manageModule,
  },
  plugins: [p]，
});
```
此时各store能够正常使用，但userModule没有进入localstorage。

**Comment by Banlangenn** [comment]
进入页面并不会存入的  ，当你修改userModule中的数据才会存入本地

，或者你看一下userModule内部是不是有问题（我把例子改了 https://codesandbox.io/s/jpw79pmr15 ）

修改 Module内的state必须是当前Module内的mutations  这是vuex的标准

**Comment by windingwind** [comment]
您好，当时应当是不论怎么mutation也无法存入的情况，不知道是什么原因，现在暂时没有用到了。您的例子似乎加载不出来？

**Comment by Banlangenn** [comment]
在试一试  ：（多等一会儿加载有些慢）==api我改了一些：大差不差
