### ISSUE TITLE
无法找到模块“vue-savedata”的声明文件。

### ISSUE THREAD

**Issue by wumingluren** [Banlangenn/vue-savedata#5]
2.0.2最新版会出现这个问题，

**Comment by Banlangenn** [comment]
https://codesandbox.io/s/jpw79pmr15

试了一下  这个用的就是最新的版本  

可以的呀

**Comment by wumingluren** [comment]
线上例子在 Storage 里面没看到存储的数据，我本地例子和线上例子一模一样也没看到保存的数据，不知道是不是因为无法找到声明文件的原因。

**Comment by Banlangenn** [comment]
https://jpw79pmr15.csb.app/

1. 有的呀 在localStorage    key 是 savedata  vaue 是密文（这个可以选择）

**Comment by wumingluren** [comment]
昨天找 savedata  key都没找到，进这个演示是正常的。

**Comment by wumingluren** [comment]
大概知道是什么问题了，初始化的时候没有存储，要改变一次值然后才触发了存储。

**Comment by Banlangenn** [comment]
### 初始化的时候  都是  写死的默认数据

**没必要去存的呀**
