### ISSUE TITLE
使用savedata过程中报错：Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Lkkpower** [Banlangenn/vue-savedata#8]
![image](https://user-images.githubusercontent.com/24646979/69126266-c4458b00-0ae2-11ea-8b2b-99c6e70239d9.png)
![image](https://user-images.githubusercontent.com/24646979/69126276-ce678980-0ae2-11ea-9a93-54c32aca7996.png)
![image](https://user-images.githubusercontent.com/24646979/69126298-d9221e80-0ae2-11ea-8462-2c35a125ec4f.png)

**Comment by Banlangenn** [comment]
模块在new Vuex 时候要添加上--
```js
const store = new Vuex.Store({
  	// ...
	modules: {
		userInfo: state,
	},
   // ....
})
```
---
另外 建议 saveName  用 英文 --- 这个name 是 本地 Storage的key，  用汉字怪怪的

### 最新添加
1.  你使用的姿势完全错了呀
2. 这个插件只能传入模块（vuex模块）   对模块内的数据 进行缓存
3.  不支持你这个中对 定制数据 缓存

**Comment by Lkkpower** [comment]
![image](https://user-images.githubusercontent.com/24646979/69199665-a1af8280-0b73-11ea-9635-5bfd72838705.png)
![image](https://user-images.githubusercontent.com/24646979/69199741-e3d8c400-0b73-11ea-8011-b5b3f8cf98c0.png)
好的，貌似还是报错

**Comment by Banlangenn** [comment]
state  必须是个模块---  这种(发了个新版本 ，把你这个报错屏蔽了)

```js
export default {
  state,
  mutations,
  actions
};
 
```

对于你这个demo  想把整个state 缓存了， 最合适的是什么都不配置就好了

```js
import createPersiste from 'vue-savedata'
// 默认全部持久化，你也可以通过一丢丢配置项,指定数据持久化
const store = new Vuex.Store({
  // ...
  plugins: [createPersiste()],
})
```
那些配置项主要作用是: 缓存指定模块的 state-
