### ISSUE TITLE
ie10 状态下报   SCRIPT1010: 缺少标识符 

### ISSUE THREAD

**Issue by zyh940305858** [Banlangenn/vue-savedata#9]

**Comment by Banlangenn** [comment]
本地用ie10  ,ie9无法复现， 按道理 应该能够支持到ie9的，
百度到： SCRIPT1010: 缺少标识符
1、出现了多余的逗号：","

2、使用了js中保留的关键词，如： default, delete 等

**Comment by zyh940305858** [comment]
我使用vue-savedata做vuex数据持久化，在ie10中遇到了SCRIPT1010: 缺少标识符的问题，把vue-savedata去掉用localstorage代替完成了兼容ie

**Comment by Banlangenn** [comment]
找到原因了，babel打包设置的 有问题
--
需要下调到ie9

**Comment by Banlangenn** [comment]
已解决
